-- 1
SELECT
    STUDENT_NO AS 학번
,   STUDENT_NAME AS 이름
,   ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2
SELECT PROFESSOR_NAME
,   PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3
SELECT PROFESSOR_NAME
,  120 - SUBSTR(PROFESSOR_SSN,1,2)
FROM TB_PROFESSOR
ORDER BY 120 - SUBSTR(PROFESSOR_SSN,1,2);

-- 4
SELECT
SUBSTR(PROFESSOR_NAME,2) AS 이름
FROM TB_PROFESSOR;

-- 5
SELECT STUDENT_NO
, STUDENT_NAME
     -- 입학년도 112 생년 88 12-88 = -76   + 100 = 24
     -- 입학년도 114 생년 95 114- 95 = 19
     -- 입학년도 199 생년 68
,EXTRACT()
,CASE WHEN SUBSTR(EXTRACT(YEAR FROM ENTRANCE_DATE),3,2) - SUBSTR(STUDENT_SSN,1,2) < 0 THEN SUBSTR(EXTRACT(YEAR FROM ENTRANCE_DATE),3,2) - SUBSTR(STUDENT_SSN,1,2) + 100
ELSE SUBSTR(EXTRACT(YEAR FROM ENTRANCE_DATE),3,2) - SUBSTR(STUDENT_SSN,1,2)
END
FROM TB_STUDENT
WHERE  100+SUBSTR(EXTRACT(YEAR FROM ENTRANCE_DATE),3,2) - SUBSTR(STUDENT_SSN,1,2) > ;
-- ,SUBSTR(STUDENT_SSN,1,2)-



-- 급여가 300만원 이상인 직원이 속한 부서를 고를 때
SELECT DEPT_CODE