SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY

FROM EMPLOYEE
WHERE (NVL(DEPT_CODE, '부서없음'), SALARY) IN (SELECT NVL(DEPT_CODE, '부서없음'), MAX(SALARY)

                                           FROM EMPLOYEE

                                           GROUP BY DEPT_CODE)
ORDER BY DEPT_CODE;

CREATE USER MYMY IDENTIFIED BY MYMY;
GRANT CONNECT, RESOURCE TO MYMY;

CREATE USER EMPLOYEE IDENTIFIED BY EMPLOYEE;
GRANT CONNECT, RESOURCE TO EMPLOYEE;

SELECT *
FROM (SELECT *
      FROM EMPLOYEE
      ORDER BY HIRE_DATE)
WHERE ROWNUM <= 5;

SELECT EMP_NAME,
       RANK() OVER (ORDER BY HIRE_DATE) AS rank
FROM EMPLOYEE
WHERE RANK() OVER (ORDER BY HIRE_DATE) <=5;

SELECT EMP_NAME
     , SALARY
     , RANK() OVER (ORDER BY SALARY DESC) AS '순위'
FROM EMPLOYEE
WHERE 순위 <=5;


SELECT
    WRITER_NM
  , OFFICE_TELNO
  , HOME_TELNO
  , MOBILE_NO
FROM TB_WRITER  (SELECT *
                FROM TB_WRITER
                WHERE WRITER_NM LIKE '김%' AND MOBILE_NO LIKE '019%')
WHERE ROWNUM=1
ORDER BY WRITER_NM;

SELECT
    WRITER_NM
  , OFFICE_TELNO
  , HOME_TELNO
  , MOBILE_NO
FROM (SELECT
                    *
                FROM TB_WRITER
                ORDER BY WRITER_NM)
WHERE WRITER_NM LIKE '김%' AND MOBILE_NO LIKE '019%' AND ROWNUM=1;

SELECT *
FROM TB_WRITER;